### ISSUE TITLE
Memory error when I put in a bunch of files. I was making a 1:1 of a world.

### ISSUE THREAD

**Issue by KingXjjj** [Haku8866/ImageStitcher#1]
1164/1273 complete...
1165/1273 complete...
Traceback (most recent call last):
  File "ImageStitcher.py", line 66, in <module>
  File "site-packages\PIL\Image.py", line 1513, in paste
  File "site-packages\PIL\ImageFile.py", line 209, in load
  File "site-packages\PIL\PngImagePlugin.py", line 649, in load_prepare
  File "site-packages\PIL\ImageFile.py", line 279, in load_prepare
MemoryError
[21792] Failed to execute script ImageStitcher

**Comment by KingXjjj** [comment]
Never mind. It just needed more ram available. But if the image is too big it gets compressed and it's not really a 1:1 anymore.
